### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CodeBrauer** [CodeBrauer/awesome-icon-fonts#1]
- [x] add contributing file
- [x] add contents
- [x] add legend
- [x] select an appropriate license
- [ ] make a PR to [sindresorhus/awesome](https://github.com/sindresorhus/awesome)

**Comment by CodeBrauer** [comment]
Also to add:
- http://www.alessioatzeni.com/metrize-icons/
- http://demo.amitjakhu.com/dripicons/
